<!doctype html>
<html <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?>>
        <style>
            .lazyload,
            .lazyloading {
                background: #f0f0f0;
                height: inherit;
                width: inherit;
            }
            .lazyloaded {
                background: transparent;
                transition: background 300ms;
            }
        </style>
        <link href="<?= $this->assetRepo->getUrl('css/styles.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
        />

        <link href="<?= $this->assetRepo->getUrl('css/print.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
              media="print"
        />

        <?php /* @escapeNotVerified */ echo $requireJs ?>
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
    </head>

    <body data-container="body"
          data-mage-init='{
              "loaderAjax": {},
              "loader": {
                  "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"
              }
          }'
          <?php /* @escapeNotVerified */ echo $bodyAttributes ?>
    >
        <?php /* @escapeNotVerified */ echo $layoutContent ?>
    </body>
</html>
