<!doctype html>
<html <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?>>
        <link href="<?= $this->assetRepo->getUrl('css/styles-m.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
        />
        <link href="<?= $this->assetRepo->getUrl('css/styles-l.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
              media="screen and (min-width: 768px)"
        />
        <link href="<?= $this->assetRepo->getUrl('mage/calendar.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
        />
        <link href="<?= $this->assetRepo->getUrl('css/print.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
              media="print"
        />

        <!-- Sample data styles moved from media -->
        <link href="<?= $this->assetRepo->getUrl('Magento_Theme/css/media.css') ?>"
              rel="preload"
              as="style"
              onload="this.rel='stylesheet'"
        />

        <script>
            !function(a){"use strict";var b=function(b,c,d){function e(a){return h.body?a():void setTimeout(function(){e(a)})}function f(){i.addEventListener&&i.removeEventListener("load",f),i.media=d||"all"}var g,h=a.document,i=h.createElement("link");if(c)g=c;else{var j=(h.body||h.getElementsByTagName("head")[0]).childNodes;g=j[j.length-1]}var k=h.styleSheets;i.rel="stylesheet",i.href=b,i.media="only x",e(function(){g.parentNode.insertBefore(i,c?g:g.nextSibling)});var l=function(a){for(var b=i.href,c=k.length;c--;)if(k[c].href===b)return a();setTimeout(function(){l(a)})};return i.addEventListener&&i.addEventListener("load",f),i.onloadcssdefined=l,l(f),i};"undefined"!=typeof exports?exports.loadCSS=b:a.loadCSS=b}("undefined"!=typeof global?global:this);
            !function(a){if(a.loadCSS){var b=loadCSS.relpreload={};if(b.support=function(){try{return a.document.createElement("link").relList.supports("preload")}catch(b){return!1}},b.poly=function(){for(var b=a.document.getElementsByTagName("link"),c=0;c<b.length;c++){var d=b[c];"preload"===d.rel&&"style"===d.getAttribute("as")&&(a.loadCSS(d.href,d,d.getAttribute("media")),d.rel=null)}},!b.support()){b.poly();var c=a.setInterval(b.poly,300);a.addEventListener&&a.addEventListener("load",function(){b.poly(),a.clearInterval(c)}),a.attachEvent&&a.attachEvent("onload",function(){a.clearInterval(c)})}}}(this);
        </script>

        <?php /* @escapeNotVerified */ echo $requireJs ?>
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
    </head>

    <body data-container="body"
          data-mage-init='{
              "loaderAjax": {},
              "loader": {
                  "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"
              }
          }'
          <?php /* @escapeNotVerified */ echo $bodyAttributes ?>
    >
        <?php /* @escapeNotVerified */ echo $layoutContent ?>
    </body>
</html>
